type Project = { id: string; title: string; goal: string; createdAt: string };
const storageKey = "karyaFrontendProjects";
const get = <T extends Element>(selector: string): T => { const el=document.querySelector<T>(selector); if(!el) throw new Error(`Missing ${selector}`); return el; };
const modal=get<HTMLElement>("#projectModal"), goal=get<HTMLTextAreaElement>("#projectGoal"), grid=get<HTMLElement>("#projectGrid"), empty=get<HTMLElement>("#projectsEmpty"), recent=get<HTMLElement>("#recentList"), count=get<HTMLElement>("#projectCount"), appToast=get<HTMLElement>("#appToast"), sidebar=get<HTMLElement>("#sidebar"), scrim=get<HTMLElement>("#sidebarScrim");
function readProjects():Project[]{ try{return JSON.parse(localStorage.getItem(storageKey)??"[]") as Project[]}catch{return[]} }
function writeProjects(items:Project[]):void{ try{localStorage.setItem(storageKey,JSON.stringify(items))}catch{} }
function escapeHtml(value:string):string{return value.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]??c))}
function titleFrom(goalText:string):string{const clean=goalText.trim().replace(/\s+/g," ");return clean.length>54?clean.slice(0,51)+"…":clean}
function showAppToast(message:string):void{appToast.textContent=message;appToast.classList.add("show");setTimeout(()=>appToast.classList.remove("show"),2400)}
function render():void{const items=readProjects();count.textContent=String(items.length);empty.hidden=items.length>0;grid.innerHTML=items.map(p=>`<article class="project-card" data-project="${p.id}"><span class="status">READY TO PLAN</span><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.goal)}</p><footer><span>Karya project</span><span>${new Date(p.createdAt).toLocaleDateString()}</span></footer></article>`).join("");recent.innerHTML=items.length?items.slice(0,5).map(p=>`<button class="recent-item" data-project="${p.id}">${escapeHtml(p.title)}</button>`).join(""):'<p class="recent-empty">Projects you create will appear here.</p>';}
function openModal(prefill=""):void{goal.value=prefill;modal.classList.add("open");modal.setAttribute("aria-hidden","false");setTimeout(()=>goal.focus(),20)}
function closeModal():void{modal.classList.remove("open");modal.setAttribute("aria-hidden","true")}
function createProject(text:string):void{const items=readProjects();items.unshift({id:crypto.randomUUID?.()??String(Date.now()),title:titleFrom(text),goal:text.trim(),createdAt:new Date().toISOString()});writeProjects(items);render();closeModal();showAppToast("Project saved locally — PostgreSQL connects later");switchView("projects");}
function switchView(name:string):void{document.querySelectorAll<HTMLElement>(".view").forEach(v=>v.classList.toggle("active",v.id===`${name}View`));document.querySelectorAll<HTMLButtonElement>(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===name));sidebar.classList.remove("open");scrim.classList.remove("open")}
document.querySelectorAll<HTMLButtonElement>(".nav-item").forEach(b=>b.addEventListener("click",()=>switchView(b.dataset.view??"home")));
["#newProjectButton","#projectsNewButton","#emptyNewButton"].forEach(s=>document.querySelector(s)?.addEventListener("click",()=>openModal()));
document.querySelectorAll("[data-close-modal]").forEach(el=>el.addEventListener("click",closeModal));
get<HTMLFormElement>("#projectForm").addEventListener("submit",e=>{e.preventDefault();if(goal.value.trim())createProject(goal.value)});
get<HTMLFormElement>("#composerForm").addEventListener("submit",e=>{e.preventDefault();const input=get<HTMLTextAreaElement>("#composerInput");if(input.value.trim()){createProject(input.value);input.value=""}});
document.querySelectorAll<HTMLButtonElement>(".suggestions button").forEach(b=>b.addEventListener("click",()=>openModal(b.textContent??"")));
get<HTMLButtonElement>("#menuButton").addEventListener("click",()=>{sidebar.classList.add("open");scrim.classList.add("open")});get<HTMLButtonElement>("#sidebarClose").addEventListener("click",()=>{sidebar.classList.remove("open");scrim.classList.remove("open")});scrim.addEventListener("click",()=>{sidebar.classList.remove("open");scrim.classList.remove("open")});
const profileButton=get<HTMLButtonElement>("#profileButton"),profileMenu=get<HTMLElement>("#profileMenu");profileButton.addEventListener("click",()=>{const open=profileMenu.classList.toggle("open");profileButton.setAttribute("aria-expanded",String(open))});get<HTMLButtonElement>("#signOutButton").addEventListener("click",()=>{try{localStorage.removeItem("karyaDemoSession")}catch{}window.location.assign("/login")});
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal();if(e.key.toLowerCase()==="n"&&!e.metaKey&&!e.ctrlKey&&document.activeElement?.tagName!=="TEXTAREA")openModal()});render();
